vim.cmd('set number')
vim.cmd('set shiftwidth=2')
vim.cmd('set autoindent')
vim.cmd('set smartindent')

require('plugins')
require('file-explorer')
require('mason-config')
require('gopls')
require('code-completion')
require('debugging')
require('key-mappings')
require('styling')
require('syntax-highlight')
require('file-finder')
require('statusbar')
require('tabs')
require('brackets')
require('indentline')
require('mybarbar')
require('flutter-config')
require('formatter')
